title: "Kuan-Hsun Tu"
description: "Embodied AI / HPC / Reinforcement Learning"
baseurl: ""
url: "https://syun413.github.io"

remote_theme: "piazzai/cvless"

# site settings
# taglong: "Embodied AI / RL / HPC"
tagshort: "Embodied AI / RL / HPC"
cv: true

# author settings
author:
  name: "Kuan-Hsun Tu"
  email: "khtu@csie.ntu.edu.tw"
  avatar: "/assets/img/avatar.jpg"

photo: "/assets/img/avatar.jpg"
joblines:
  - National Taiwan University, CSIE
  - Robotics & Reinforcement Learning
  - High-Performance Computing (HPC)

address: Taipei, Taiwan
phone: ""

# profile links
profile:
  github: https://github.com/syun413

# build settings
permalink: /blog/:title/
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-remote-theme
  - jekyll-paginate

sass:
  sourcemap: never

paginate: 5
